spring:
  datasource:
    password: password
    username: root
    url: 'jdbc:mysql://localhost:3306/tiketeraDB?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC'
  jpa:
    hibernate:
      ddl-auto: update