server:
   port: 8084
spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tiketeraDB?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
      username: root
      password: password
      jpa:
         hibernate:
            ddl-auto: update
         properties:
            hibernate: null