server:
    port: 8002
spring:
    application:
        name: service-users
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: password
        url: jdbc:mysql://localhost:3306/tiketeraDB?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                show-sql: true
        show-sql: true
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8099/eureka/