spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/tiketeraDB?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC'
    password: password
    username: root
  jpa:
    hibernate:
      ddl-auto: update